2022-01-12 12:41:46,515	INFO monitor.py:527 -- Starting monitor using ray installation: /home/reza/anaconda3/lib/python3.8/site-packages/ray/__init__.py
2022-01-12 12:41:46,515	INFO monitor.py:528 -- Ray version: 1.9.0
2022-01-12 12:41:46,515	INFO monitor.py:529 -- Ray commit: 92599d9127e228fe8d0a2d94ca75754ec21c4ae4
2022-01-12 12:41:46,515	INFO monitor.py:530 -- Monitor started with command: ['/home/reza/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py', '--logs-dir=/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-12_12-41-44_891232_9622/logs', '--redis-address=131.215.21.210:6379', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--redis-password=5241590000000000', '--monitor-ip=131.215.21.210']
2022-01-12 12:41:46,520	INFO monitor.py:192 -- Starting autoscaler metrics server on port 44217
2022-01-12 12:41:46,522	INFO monitor.py:206 -- Monitor: Started
2022-01-12 12:41:46,586	INFO autoscaler.py:214 -- StandardAutoscaler: {'cluster_name': 'default', 'max_workers': 0, 'upscaling_speed': 1.0, 'docker': {}, 'idle_timeout_minutes': 0, 'provider': {'type': 'readonly', 'use_node_id_as_ip': True}, 'auth': {}, 'available_node_types': {'ray.head.default': {'resources': {}, 'node_config': {}, 'max_workers': 0}}, 'head_node_type': 'ray.head.default', 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': [], 'worker_start_ray_commands': [], 'head_node': {}, 'worker_nodes': {}}
2022-01-12 12:41:46,587	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:41:46.587715 ========
Node status
---------------------------------------------------------------
Healthy:

Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:


Demands:
 (no resource demands)
2022-01-12 12:41:51,593	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:41:51.593763 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:41:56,601	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:41:56.601871 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:01,607	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:01.607615 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:06,613	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:06.613831 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:11,622	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:11.622017 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:16,629	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:16.629496 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:21,633	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:21.633439 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:26,639	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:26.639541 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:31,646	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:31.645998 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:36,650	INFO autoscaler.py:278 -- 
======== Autoscaler status: 2022-01-12 12:42:36.650058 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_63590236badecdba02e7161758bf9d60aa3e0e5eb094b6a0eaeb9b44
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/12.0 CPU
 0.0/1.0 GPU
 0.0/1.0 accelerator_type:GTX
 0.00/16.701 GiB memory
 0.00/8.351 GiB object_store_memory

Demands:
 (no resource demands)
2022-01-12 12:42:38,048	ERROR monitor.py:398 -- Error in monitor loop
NoneType: None
2022-01-12 12:42:38,049	ERROR gcs_utils.py:136 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1642020158.049105710","description":"Error received from peer ipv4:131.215.21.210:34473","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Socket closed","grpc_status":14}"
>
2022-01-12 12:42:38,049	ERROR gcs_utils.py:142 -- Connecting to gcs failed. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1642020158.049105710","description":"Error received from peer ipv4:131.215.21.210:34473","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Socket closed","grpc_status":14}"
>
